name : Lakshays version of CI

on:
  pull_request:
    branches:
      -main
    paths:
      - "web/**"
  push:
    branches:
      -main
    paths:
      -'web/**'

jobs:
  test :
    runs-on : ubuntu-latest
    name : checking
    defaults:
      run:
        shell : bash
        working-directory : ./web
    steps:
      - uses : actions/checkout@v2
        name : 'Checkout repository'

      - name : 'Install dependencies'
        run : npm install

      - name : 'Run tests'
        run : npm run test
