name : Lakshays version of CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'web/**'
  push:
    branches:
      - main
    paths:
      - 'web/**'
  workflow_dispatch:

jobs:
  test :
    runs-on : ubuntu-latest
    name : checking
    defaults:
      run:
        shell : bash
        working-directory : ./web
    steps:
      - uses : actions/checkout@v2
        name : 'Checkout repository'

  Linter :
    name : Linting
    runs-on : ubuntu-latest
    defaults :
      shell : bash
      working-directory : ./web

    steps:
      - name : "checkinout repo"
        run : actions/checkout@v2

      - name : "Install Dependencies"
        run : npm install
  

      - name : 'Install dependencies'
        run : npm install

      - name : 'Run Linter'
        run : npx standard -v
